CREATE DATABASE mydb DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
use mydb;
CREATE TABLE if NOT EXISTS user_info(
    userinfo_no INT(20) AUTO_INCREMENT,
    user_id INT(20) UNIQUE KEY,
    PRIMARY KEY (userinfo_no)
) ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

CREATE TABLE if NOT EXISTS order_info(
    order_id INT(20) AUTO_INCREMENT,
    user_id INT(20) UNIQUE KEY,
    state VARCHAR(20),
    PRIMARY KEY (order_id),
    FOREIGN KEY (user_id) REFERENCES user_info(user_id) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

CREATE TABLE if NOT EXISTS order_detail_info(
    order_detail_id INT(20) AUTO_INCREMENT,
    order_id INT(20),
    menu VARCHAR(20),
    quantity INT(10),
    PRIMARY KEY (order_detail_id),
    FOREIGN KEY (order_id) REFERENCES order_info(order_id) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;