CREATE DATABASE mydb DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
use mydb;
CREATE TABLE if NOT EXISTS user_info(
    userinfo_no INT(20) AUTO_INCREMENT,
    user_id INT(20) UNIQUE KEY,
    PRIMARY KEY (userinfo_no)
) ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

CREATE TABLE if NOT EXISTS order_info(
    order_id INT(20) AUTO_INCREMENT,
    userinfo_no INT(20),
    name VARCHAR(20),
    quantity INT(10),
    state VARCHAR(20),
    PRIMARY KEY (order_id),
    FOREIGN KEY (userinfo_no) REFERENCES user_info(userinfo_no) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;